### ISSUE TITLE
improve playground loading times

### ISSUE THREAD

**Issue by lipp** [lipp/doclets#137]
doclets with many playgrounds get stuck, because of pretty slow load times of the playgrounds supported by the **awesome** tonicdev.

example:
https://doclets.io/dleitee/strman/master

how can this be solved? the main focus should be to allow to user to scroll the page, even if not all playgrounds are loaded. this is the code which loads / embeds the playgrounds:

https://github.com/lipp/doclets/blob/master/views/doclayout.jade#L36

**Comment by tolmasky** [comment]
Hi, the real solution is for us to make them load faster. However, while we work on that, I have had success simply delaying the loading. If you look at this blog post I wrote, it loads many examples and still remains fast scrolling: http://tolmasky.com/2016/03/24/generalizing-jsx/ . The code is in that same file.

**Comment by lipp** [comment]
@tolmasky Thank you very much!!!! 💯  I'll try to integrate your temp solution.

**Comment by lipp** [comment]
@tolmasky ... sorry... could you please point me to the piece of code which handles the loading/delaying/whatever of the tonicdev examples? Thanks!!!

**Comment by tolmasky** [comment]
Sure, its just:

```
var samples = document.querySelectorAll(".highlighter-rouge");
var index = 0;
var count = samples.length;

function load(aSample)
{
    var source = Tonic.sourceFromElement(aSample);

    aSample.innerHTML = "";

    Tonic.createNotebook(
    {
        // the parent element for the new notebook
        element: aSample,

        // specify the source of the notebook
        source: source,
        nodeVersion: "4.x.x",
        onLoad:function (aNotebook)
        {
            //aNotebook.evaluate();
        }
    });
}

function loadAll(samples, index)
{
    while (index < count && samples[index].tagName !== "DIV")
        ++index;

    if (!(index < count))
        return;

    load(samples[index]);
    
    setTimeout(loadAll, 1000, samples, index + 1);
}

loadAll(samples, 0);


```

**Comment by lipp** [comment]
@tolmasky Thanks 💯  again! This is in now...
As long as the tonic devs don't load faster, this is probably an as-good-as-possible solution, so i'll close this for now.

**Comment by lipp** [comment]
@dleitee this improves the strman usability a lot (though, still not great)
https://doclets.io/dleitee/strman/v1.3.0

**Comment by dleitee** [comment]
@lipp Thank you, I will see doclets project and verify if I can contribute with improvements and fixes.

**Comment by tolmasky** [comment]
Another strategy is to do what lodash has done: lodash.github.io (show the embed/ run it when clicked)
