### ISSUE TITLE
Separate static and instance members

### ISSUE THREAD

**Issue by janmeier** [lipp/doclets#161]
For example https://doclets.io/sequelize/sequelize/doclets#dl-Model

![image](https://cloud.githubusercontent.com/assets/1210224/16576566/4a2fc916-4290-11e6-9096-265226b889a3.png)

Since this class has a lot of members, it would be nice to be able to clearly see which are instance and which are static

**Comment by lipp** [comment]
Good idea! Any suggestions how to make this visible? (icon, color, font style)?

**Comment by janmeier** [comment]
I was thinking two separate lists (But then again, I'm not very design minded...) Guess we could also just show instance first and then static, maybe with a color difference, like in the lefthand-side

**Comment by lipp** [comment]
Sure... 
Members:

and 
Static Members:

.... obvious ...

**Comment by felixfbecker** [comment]
I would say a grey divider in both the members list and the links on the left side. But I would first list the static members, then the instance members. And of course only show the headline if there are actually items of that kind.

**Comment by lipp** [comment]
@felixfbecker @janmeier done. Is this ok for you?
https://doclets.io/sequelize/sequelize/doclets#dl-Model

**Comment by felixfbecker** [comment]
@lipp Looks great, but would a speration be possible also for the navigation pane on the left?

**Comment by lipp** [comment]
@felixfbecker the nav on the left will receive some improvements... maybe this would be a good idea...
