### ISSUE TITLE
Documentation breaks when formatting is wrong

### ISSUE THREAD

**Issue by morkro** [lipp/doclets#163]
Hello :wave:,

it looks like the documentation is broken once a JSDoc comment has incorrect formatting.
Here are two occurrences I found:

- If you go to [this part](https://doclets.io/morkro/atom-emoji-syntax/master#dl-EmojiStyleSheet-add) of my documentation, you see that it stops reporting in the middle of the sentence. I assume the chevron (`<atom-styles>`) in my description causes this problem?
![screen shot 2016-07-07 at 11 07 50](https://cloud.githubusercontent.com/assets/2461956/16648182/15747434-4433-11e6-8e43-6b298d6d72b6.png)

- The documentation for my [`createElement()`](https://doclets.io/morkro/atom-emoji-syntax/master#dl-EmojiStyleSheet-createElement) method also stops with the description, and everything after that is left blank on the page. I also guess it's because I used probably unknown formatting of an optional parameter which also happens to accept two different types: `@param {(Number|String)}`. 
![screen shot 2016-07-07 at 11 07 42](https://cloud.githubusercontent.com/assets/2461956/16648189/1be28a9a-4433-11e6-8d51-418bd0b7dc5c.png)

This makes me also think what the correct declaration of an optional parameter is, which happens to accept multiple types.

Anyway, great work! Really like this project 😀 

Best,
Moritz

**Comment by lipp** [comment]
@morkro Thanks for reporting! This is an html escaping thingy. JSDoc comments are allowed to contain HTML and Markdown. So the description potentially (and intentionally) contains HTML tags in string. 

Could you try to wrap your tags in backticks? This hopefully instructs JSDoc to do the right thing...

PS: Happy you like Doclets!

**Comment by morkro** [comment]
Well TIL JSDoc comments are Markdown 😁 . 
Thanks for the help, I updated all my JSDoc comments and that fixed the issue. Everything looks [fresh](https://doclets.io/morkro/atom-emoji-syntax/master) now. 👍

**Comment by lipp** [comment]
👍 Great!!! You are welcome! If you like Doclets, spread the word 😀
