### ISSUE TITLE
doclets.io not picking up changes

### ISSUE THREAD

**Issue by Alxandr** [lipp/doclets#174]
I'm trying to progressively add documentation to my repository over at https://github.com/YoloDev/nitter using the `add-to-doclets` branch. However, doclets.io stopped showing my changes after a few updates, and now I can't seem to get it to work again. I've even tried deleting and recreating the branch, but it doesn't work. Please help.

**Comment by tf** [comment]
For the `add-to-doclets` branch it is still working for me. But updates on other branches are no longer detected, and also detecting new branches only worked in a single case.

**Comment by lipp** [comment]
Hi! Thanks for using doclets... and sorry for the trouble.

I cloned your repo and the add-to-doclets branch works just fine for me. I also ran some changes in the README.md to see if the generated pages update. Everything worked as expected.

https://doclets.io/lipp/nitter/add-to-doclets/overview

However, your latest add-to-doclets branch commit is ahead/newer with respect to the doclets.io version. @Alxandr is your repo still enabled within doclets? If so, could you please check your **repo webhook settings in github**? There should be an entry for doclets.io service.

There were some fixes concerning the doc generator workqueue going on some days ago. But this shouldn't have any impact...

@tf per default master and add-to-doclets branches are enabled. [.doclets.yml](https://doclets.io/doclets.yml)

**Comment by Alxandr** [comment]
![image](https://cloud.githubusercontent.com/assets/112334/16977857/016fa5aa-4e59-11e6-8c1d-39d44fbe2089.png)

I'm guessing the issue stems from me doing a forced update to the branch (which doclets really need to support). I did `git commit --amend` followed by `git push -f`. This makes the branches out of sync and then force-updates the one on github. So maybe your cloning code is breaking?

**Comment by lipp** [comment]
@Alxandr thanks for the details. I guess you are right... 
Do you know, how to determine if the cloned repo got out-of-sync?
This is the code, which handles the checkout on push events (to help you get an idea what is going on right now...):
https://github.com/lipp/doclets/blob/master/lib/repo.js#L78

**Comment by Alxandr** [comment]
Quick googling gave me this: http://stackoverflow.com/a/3278427/213323 which is probably exactly what you need. Translating the bash-script to JS should also be fairly easy. If the branches has diverged `git pull` will fail as far as I know. Although, what you could (probably) do, which (I think) would work regardless is just do `git fetch origin master` followed by `git checkout origin/master`. Or even better, do the git fetch, followed by figuring out the SHA1 of `origin/master` and then do `git checkout <SHA1>`. This will put you in a detached HEAD. So it doesn't really much matter what you do/what is done. Run the build from there, publish it, and you can just repeat the process next time.

**Comment by tf** [comment]
@lipp Ah, I forgot about that. I guess I got confused since I pushed a branch `doc-mod` and saw it appear [in the branch list](https://doclets.io/tf/pageflow) and after following the link it simply [said I was missing the config file](https://doclets.io/tf/pageflow/doc-mod). 

But when I push other branches now, they do not show up. I see a [successful webhook call](https://gist.github.com/tf/ba2abe6d2aa636dd5335bb864b6224ea), though. Maybe I've hit some sort of maximal count of items in the branch list?

**Comment by tf** [comment]
After further tests, I can confirm that this is mainly related to branches that have been force pushed. Still not completely sure why some branches did not show up in the overview. But for new branches with a config file, everything seems to work fine.

I guess `repo.js` should rather `git fetch` and `git reset --hard origin/branch` instead of trying to checkout the branch and pull.

**Comment by Alxandr** [comment]
@lipp for now, could you just make a button somewhere that "force updates" a branch? So that when it gets stuck we can get it up and working again? And we can look at bettering it later. I can probably get involved with helping, even though I violently disagree with the no-semicolon convention :-/

**Comment by lipp** [comment]
@Alxandr thanks for the offer. Your help is very welcomed 👍 
However, I'm going in vacation for 3 weeks, so unfortunately I won't risk  to make any quick-changes.
I hope you can proceed with your project and return to doclets as soon as this issue gets resolved.

**Comment by lipp** [comment]
@Alxandr @tf just added @tf's improvement. Could you give it a try?

**Comment by Alxandr** [comment]
Seems to be working :+1:

**Comment by lipp** [comment]
Great! Thanks!!!
