### ISSUE TITLE
nps-utils doclets not rendering

### ISSUE THREAD

**Issue by kentcdodds** [lipp/doclets#307]
I just added doclets to my new module `nps-utils` [here](https://doclets.io/kentcdodds/nps-utils/master) and as you can see, it's able to render the Overview (the README), but it's not rendering the API (based on the code's JSDoc in the [`src`](https://github.com/kentcdodds/nps-utils/blob/master/src/index.js) direcotry). Any tips are appreciated!

**Comment by lipp** [comment]
Could you remove the `packageJson` from .doclets.yml?

**Comment by kentcdodds** [comment]
That didn't work 😕
