### ISSUE TITLE
error on 'sync'

### ISSUE THREAD

**Issue by fridgamarator** [lipp/doclets#47]
url is : https://doclets.io/sync
response is : `Err {"message":"Bad credentials","documentation_url":"https://developer.github.com/v3"}`

I tried to log out and revoke Doclets authorization from my github account, but this didn't seen to work.

**Comment by lipp** [comment]
@fridgamarator thanks for reporting. Not sure what causes this right now. ... did you manually change your webhook settings in your repo? Did login succeed before?

**Comment by fridgamarator** [comment]
I added a public repo to Doclets just to test, but removed the repo from Doclets because it didn't have any documentation.  I then created another private repo in github which had documentation and tried to Re-Sync repositories.  That is when I get this error.  I didn't adjust any webhook settings in my github repos.

**Comment by zandaqo** [comment]
Same error, different scenario: I just joined, but forgot to allow Doclet.io access to my organization's repos. To fix that, I logged out, revoked access to my account in Github settings, and then signed up again this time granting access to organization. However, it still doesn't show my organization's repos and upon clicking on re-sync shows the above mentioned error. I checked my Github settings for both the user and organization and they are both granting third-party access to Doclets.io.

**Comment by lipp** [comment]
thanks for the detailed reports! working on that. sorry for the trouble!

**Comment by lipp** [comment]
@fridgamarator @zandaqo could you please try to delete all the cookies for doclets.io
(if you visit https://doclets.io in the address bar). This probably will do the trick for now.

**Comment by zandaqo** [comment]
@lipp Nope, doesn't seem to work. Tried removing all cookies, logging in and out, in Chrome and FF, no changes: gives the same error upon clicking on the re-sync button.

**Comment by lipp** [comment]
:( thanks for trying. i'll reach you if this is fixed.

**Comment by lipp** [comment]
@zandaqo @fridgamarator @joscha This should be fixed now. On your user/account page you will be asked to reauthenticate.
Please let me know how this works for you.

**Comment by lipp** [comment]
organization repos and private repos are still not available :( ... working on that.

**Comment by zandaqo** [comment]
Sorry for the dilatory response. It works fine for me, thank you! Now eagerly waiting for the org reps to finally try this thing =)

**Comment by lipp** [comment]
@fridgamarator @joscha did this work for you too?

**Comment by lipp** [comment]
@fridgamarator @joscha can i close this?

**Comment by joscha** [comment]
@lipp yes, it works.

**Comment by lipp** [comment]
@joscha thanks! Everything working for you? Missing something? Let me know if you need something!

**Comment by joscha** [comment]
@lipp Organization repos please :)

**Comment by lipp** [comment]
@joscha working on it right now :)  hope public orgas/repos are ok for you for the start...

**Comment by lipp** [comment]
@joscha did you the the embedded "playground" stuff? do you like it?

**Comment by joscha** [comment]
@yes, talking about public ones - no, I did not see any embedded playground?!

**Comment by lipp** [comment]
https://doclets.io/lipp/acme-jsdoc-example/master#dl-greet

this is a pretty useless example ... but it shows the way it works. you can write "real" node.js / javascript code and require anything you want from npm.
i think this could really boost the power of examples as you can actually execute them and play around.

**Comment by joscha** [comment]
ah, awesome! I really like it, unfortunately tonic has some problems with es6 code sometimes, but integrating it directly is brilliant!

**Comment by lipp** [comment]
glad you like it! im not sure right now how to enable it. there are three possibilities i see:
1) use non standard @playground tag
2) make all @example playgrounds
3) render static and offer a button "try as tonic" which embeds the code into tonic view

which do you prefer?

**Comment by joscha** [comment]
what about allowing custom tags and a widget definition for it - that way I could add a
```
@tonicdev src/bla/example22.js
```
that gets rendered like a playground and a 
```
@jsfiddle src/browser/example54.js src/browser/file.css
```
that gets rendered in jsFiddle style based on what the widget thinks is best.

**Comment by lipp** [comment]
that's a great idea! don't know if jsfiddle or others are as easy to embed as tonic ...?
but that would take the "live" example thingy to the max :)
i'll open a "feature" ticket!

**Comment by joscha** [comment]
We built something similar for our [AUI docs](https://docs.atlassian.com/aui/latest/docs/auiselect2.html) - see the code block in there and the buttons to export it to JSBin or JSFiddle - it uses a library called [Sandy](https://bitbucket.org/atlassianlabs/sandy). If you write a plugin architecture, I'd write a plugin that uses Sandy. Alternatively I could write one that creates an embedded jsFiddle view.

**Comment by lipp** [comment]
Awesome. that's very interesting. thanks for your offer. if this comes near (orga/private stuff done) i'll be happy to reach you again. how can i reach you best?

**Comment by joscha** [comment]
@lipp cool! My github profile has my email, that's easiest I think.

**Comment by lipp** [comment]
:100:

**Comment by fridgamarator** [comment]
sorry for my delayed response, yes this is working for me now

**Comment by lipp** [comment]
@fridgamarator thanks for your feedback!
