### ISSUE TITLE
Inconsistent documentation

### ISSUE THREAD

**Issue by meteormanaged** [lipp/doclets#49]
Regarding information at: https://doclets.io/doclets.yml

lib/dir declaration:

![image](https://cloud.githubusercontent.com/assets/10685349/13327927/fe750a3c-dbb9-11e5-99cb-964992779d60.png)

Image seems to show and describe a "dir" option with "lib" parameter.

![image](https://cloud.githubusercontent.com/assets/10685349/13327955/2473f77a-dbba-11e5-88ba-dde9ed89b6ca.png)

Example 3 shows the same.

![image](https://cloud.githubusercontent.com/assets/10685349/13327968/3537256e-dbba-11e5-82c3-0cde0d2961b3.png)

Explanation shows a "lib" option, but no "dir" option.

**Comment by lipp** [comment]
Thanks! You are totaly right. The "explained" section is wrong. I'll fix it.

**Comment by lipp** [comment]
fixed with bf08b5a
