### ISSUE TITLE
Organization Repo Support

### ISSUE THREAD

**Issue by jenius** [lipp/doclets#50]
Is there any way to add repos from an organization? Would be amazing!

**Comment by lipp** [comment]
support of private repos and organizations are coming soon!

**Comment by jenius** [comment]
Awesome, thanks for your great work here! Let me know if there's anything that I could help with :grin:

**Comment by nicky-lenaers** [comment]
Would love to see private repo's added aswell :+1:

**Comment by lipp** [comment]
@jenius @nicky-lenaers added repo support. You will be prompted for more access-rights and then using "re-sync" button should bring in your orga repos. Would be great to here if orgs work for you! Cheers!

**Comment by nicky-lenaers** [comment]
You guys are moving fast, great work :+1:  I currently don't have a orga repo, so waiting for #46 to be resolved. Looking forward to it!

**Comment by jenius** [comment]
Nice! I'm seeing some org repos now, but for some reason not all of them. Could provide an example if that helped but it's specific to my account...

**Comment by lipp** [comment]
:( nginx timeout ... not so good...
you should see all public orga repos you have admin access to.
admin right are required to enable webhooks.

**Comment by lipp** [comment]
btw: thanks for trying!

**Comment by lipp** [comment]
@jenius do you see all of your "public-orga-repos-you-are-admim-in"?

**Comment by lipp** [comment]
@jenius the steps are basically explained here: https://youtu.be/V87knrNqT0k
the order is important
1) add repo to doclets
2) add .doclets.yml file to your repo (root dir)
3) push to github (per default 'master' and 'add-to-doclets' branches will be built)
don't hesitate to ask.

**Comment by jenius** [comment]
@lipp got it, it was an admin issue, thanks! is doclets down right now though?

**Comment by jenius** [comment]
Ok, it appears to be back up. I just can't fully test this because I get a gateway timeout whenever I try to sync repos :cry:

**Comment by zandaqo** [comment]
@lipp Works great for me, didn't even need to re-sync. Thanks!

**Comment by lipp** [comment]
@jenius our hoster (digital ocean) has dns issues :( 
they don't know how long it takes to fix it. sorry for that!

**Comment by lipp** [comment]
@zandaqo great. thanks for the feedback! i'll close this issue as it seems organization repos are working.
