### ISSUE TITLE
Will Doclets stay free for open source? 

### ISSUE THREAD

**Issue by tf** [lipp/doclets#51]
Doclets looks really promising. Will it stay free for open source projects once beta phase is over?

**Comment by lipp** [comment]
Thanks! Yes, doclets.io will definitely stay free for open source projects forever!

**Comment by tf** [comment]
That's great news! I'd suggest mentioning that on the marketing site since it's a big plus from my point of view.

**Comment by lipp** [comment]
@tf done. you think it's clear enough or should point out "forever"?

**Comment by tf** [comment]
I think it's clear now. Thanks!
