### ISSUE TITLE
Support for @since tag

### ISSUE THREAD

**Issue by tf** [lipp/doclets#52]
It looks like the value of the `@since` tag is currently not visible in the generated doc. I always find it nice to see since when a certain feature is present.

Example: https://doclets.io/tf/pageflow/add-to-doclets#dl-pageflow-Features

**Comment by lipp** [comment]
Thanks for reporting. Not all tags are supported at this time. But they all will be added soon. 

The docs will be updated automatically, so just give me some time. I'll let you know when @since is available.

**Comment by tf** [comment]
That was fast! :+1:
