### ISSUE TITLE
Support for Backbone style classes

### ISSUE THREAD

**Issue by tf** [lipp/doclets#53]
At the moment, members of classes defined with an `.extends({...})` pattern get listed as part of the global scope. Having to put a `@memberof` tag on all members would be a lot of bloat. Is there an alternative? This might also be the wrong repo to ask this question since it might simply be a general JSDoc issue?

**Comment by lipp** [comment]
Yes you are right. Would be nice to have this recognized automatically. As you said this is unfortunately beyond the scope of doclets.io . When JSDoc generator supports this, doclets.io will have it too!
