### ISSUE TITLE
JSDoc plugins

### ISSUE THREAD

**Issue by zandaqo** [lipp/doclets#62]
Hi, 

Are you planning to support JSDoc plugins?

**Comment by lipp** [comment]
what plugins are you thinking of?

**Comment by zandaqo** [comment]
@lipp I was thinking of allowing any custom plugin, just like JSDoc does. Personally, I use JSDoc's underscore, and a few of my own, like [false-booleans](https://github.com/zandaqo/jsdoc-plugin-false-booleans) and [named-defaults](https://github.com/zandaqo/jsdoc-plugin-named-defaults). They are pretty handy when it comes to tailoring JSDoc to one's coding style.

**Comment by lipp** [comment]
@zandaqo nice work! added plug-in support to the feature list. at the moment i am still working on more basic things.

**Comment by tf** [comment]
Plugins would probably have to be whitelisted somehow, right? It basically means running arbitrary code on your infrastructure...

**Comment by lipp** [comment]
yes. maybe there will be a list of plugins you can choose from. unfortunatly this feature will have to wait for orga and private support being implemented.

**Comment by zandaqo** [comment]
>It basically means running arbitrary code on your infrastructure...

@tf Indeed. That was my main concern about this feature: whether or not the author(s) planned infrastructure in the way that might allow that scenario in the future.

@lipp Ideally you would want to "containerize" each run of jsdoc to mitigate the security/performance risks. Even with whitelisted plugins, or no plugins at all, there is a possibility that jsdoc might hung up on a given code. I'm not yet familiar enough with your infrastructure to say whether it's already the case, or how to make it so, but it's something worth considering in the long run.

That said, I support the idea of maintaining a set of whitelisted plugins. Not just for the sake of allowing users to use them, but if and when doclets.io decide to add extra features to JSDoc3 (like allowing non-orthodox flavors of JSDoc, e.g. Closure and the likes), IMO it would be easier, faster, and more user friendly to do that by creating plugins for JSDoc3, rather than, say, try to push modification into JSDoc3 itself. 

Speaking on implementation, the way I see it, if we go with whitelisted plugins, all it takes to implement this feature is a) decide where and how to store the whitelisted plugins, b) add an option to .doclets.yaml where user lists the needed plugins, c) while [gathering](https://github.com/lipp/doclets/blob/master/lib/gather.js#L31) configs just create a new jsdoc config file for each run with the required options, instead of trying to push them all through the command line. That is all if I'm not missing something. If we can settle/implement the first parts (how and where to store plugins), I'm willing to help with the last part.
