### ISSUE TITLE
Support @lends tag

### ISSUE THREAD

**Issue by MattiSG** [lipp/doclets#66]
Hi,

Thanks a lot for doclets! Finally looks like a way to make the value of documentation more tangible  :)

I had a surprise when trying to add it to [Watai](https://github.com/MattiSG/Watai), though: some classes are not parsed properly, and their methods are parsed as globals.
It seems to me the issue is related to the [`@lends`](http://usejsdoc.org/tags-lends.html) syntax.

Example: [result](https://doclets.io/MattiSG/Watai/add-to-doclets#dl-quitBrowser) and [source](https://github.com/MattiSG/Watai/blob/master/src/controller/Runner.js#L283).

Cheers,
Matti

**Comment by lipp** [comment]
Thanks for reporting! Happy you like and doclets and give it a try!
Maybe you are missing the @class before "var Runner = ". At least this is how the example shows...
Could you give this a try?

**Comment by lipp** [comment]
... you maybe want to do this also "/** @lends Runner.prototype */ since I guess the methods are instance methods (and not statics)

**Comment by MattiSG** [comment]
No, I'm using the `@lends`/`@constructs` couple, as documented [here](http://usejsdoc.org/tags-lends.html) (paragraph “Documented with a constructor”).

I might be missing the `.prototype`, though. This used to work with JSdoc2, testing now with JSdoc3 it indeed seems to have broken. I'll get back to you with further testing.

**Comment by lipp** [comment]
sorry, was missing that. indeed this should work if the docs are right.

**Comment by MattiSG** [comment]
The `.prototype` is equivalent to `#`, which I already added.

There is, however, an issue with this `@lends`/`@constructs` parsing in JSdoc: jsdoc3/jsdoc#343.

**Comment by lipp** [comment]
@MattiSG thanks for keeping me updated. so this seems a jsdoc issue. may i close this for now?

**Comment by MattiSG** [comment]
Sure  :)
