### ISSUE TITLE
Doclets not picking up 1 file

### ISSUE THREAD

**Issue by ericuldall** [lipp/doclets#75]
For some reason doclets (https://doclets.io/the-letter-e-production/Express-MVC/add-to-doclets) is not picking up the follwing file:
https://github.com/the-letter-e-production/Express-MVC/blob/add-to-doclets/lib/Router.js

Any idea why this is happening?

**Comment by lipp** [comment]
@ericuldall that's strange. no idea why this file is skipped. i'll look into this wed/thu as i am in easter vacations right now... 
sorry for the trouble and thanks for using doclets!

**Comment by ericuldall** [comment]
Thank you.

**Comment by lipp** [comment]
@ericuldall the jsdoc parser complains about the usage of the ("future") keyword interface. On Express-MVC master jsdoc complained about lib/Log/Utils.js and lib/Router.js . renaming the "interface" vars fixes this.

**Comment by ericuldall** [comment]
ah, okay. I'll check that out later. Is there any way you can make errors in building doclets available in the dashboard? Seems this could have been an easy fix if I know what the error was.

**Comment by lipp** [comment]
@ericuldall indeed, error handling / reporting has to be improved (well there is no such thing yet)! I'll create an issue for that. thanks!

**Comment by lipp** [comment]
@ericuldall btw: sorry it took so long!
