### ISSUE TITLE
Documenting remote files

### ISSUE THREAD

**Issue by zandaqo** [lipp/doclets#76]
Hi,

This might seem a bit far-fetched, but just in case... wouldn't it be nice to be able to specify for documentation files that do not belong to the immediate repository (remote files)?

Possible use cases:
1. documenting dependencies that don't have their own documentation;
2. creating a centralized documentation for a modularized library without loading/duplicating all libraries in the central repository.

Another way of solving the second scenario would be for doclets.io to allow creating a centralized entry point for docs generated for each module, but IMO that would a lot harder to implement than just loading remote files, which also solves the first scenario.

**Comment by lipp** [comment]
That's interesting. Actually I want to allow referencing other doclets and their items (classes, functions etc) I think this will get interesting as the user base and the number of projects documented with doclets grows.

Anyhow including "external " stuff is on the list.

**Comment by zandaqo** [comment]
To give an example, I'm rolling out our in-house MV* library [Compago](https://github.com/scriptare/compago) which is basically a [collection of libraries](https://github.com/scriptare) loosely coupled through the use of common event emitter. Each module is autonomous to a degree, but they're better together, so we have a central repository.  The central repository just keeps configs for package managers to make it possible to install the whole bunch in one go for. Now, to make a centralized documentation/API reference I have to either include each module's code into the central repository or generate docs offline and push the results back. Since managing submodules in git is a lot of hassle, I'm currently experimenting with offline generation: http://scriptare.github.io/compago/api/

It would save a lot of trouble for devs in a similar situation to just be able to link to either "external" files for generation or to create a centralized entry point for existing docs of submodules. IMO the former is easier to implement, while the later might be more user friendly in the long run. Though nothing prevents from having both.

**Comment by lipp** [comment]
So would it be ok for you to have one documentation for each "sub" module and having one additional aggregation module which links through markdown article and/or usage of @external api doc pointing to the subs? (Writing from mobile su**s)

**Comment by zandaqo** [comment]
If it can more or less seamlessly "stitch" those submodules together in the aggregated module it would be IMO the best solution (for the case at hand) and I personally don't mind manually placing `@external` tags (if you mean to do it with tags).

The reason I suggested allowing to just list the needed external files in .doclets.yml and feed them to jsdoc is that: a) it's technically a lot easier/quicker to implement; b) accounts for the case when the dependency isn't using doclets; c) or there are so many micro-modules that the author would rather not waste time managing separate doclets for each of them.

**Comment by lipp** [comment]
@zandaqo ok. the variant using external files / links from within .doclets.yml has some advantages and I guess your are right that it might be not so difficult to implement. this would work "out of the box" just for publicly available source though. there would be no webhooks, too. so changes would have to be polled :( 
what do you think? (back on keys again !)

**Comment by zandaqo** [comment]
@lipp I'm all for it. As I see it, we just need to hook up a simple loader for external files on the gathering step before feeding the results to jsdoc. If you need a hand with it, I can take a swing at it.

> there would be no webhooks, too. so changes would have to be polled :( 

Yes, I thought about that. As a solution, how about adding a button to allow manually re-running doclets generation? Like how Travis CI allows to re-run tests. Does GitHub's API allow such scenario?
