### ISSUE TITLE
@ignore ignored

### ISSUE THREAD

**Issue by joscha** [lipp/doclets#79]
a JSDoc annotation like this:

```
  /**
   * @ignore
   */
  some symbol
```

should exclude the following symbol from showing up in the documentation.

**Comment by lipp** [comment]
Thanks for reporting! Will be fixed soon.

**Comment by lipp** [comment]
@joscha this will be "online" in some hours. i'll let you know.

**Comment by lipp** [comment]
@joscha ok it is online. maybe you could give it a try and say if it is working for you?

**Comment by joscha** [comment]
@lipp is there a way to re-generate the documentation for a branch without a commit?

**Comment by lipp** [comment]
@joscha not yet. Actually you should not need this in this case as the changes affect the rendering step. Reloading the api doc page in the browser should be enough.

**Comment by joscha** [comment]
seems to work, thank you!
