### ISSUE TITLE
Support for nested options

### ISSUE THREAD

**Issue by janmeier** [lipp/doclets#82]
Currently nested and top-level parameters are rendered in a single list - which can become very long, see below 

![image](https://cloud.githubusercontent.com/assets/1210224/14151561/d6375c9a-f6ae-11e5-82fa-48bc7a804819.png)
Which is generated from https://github.com/sequelize/sequelize/blob/35e68f67b9be2702109157b6d066781555d43202/lib/model.js#L1314-L1344

Regular jsdoc shows this as a nested table, but keeping with the doclets list structure we could go for nested lists instead - note that I also removed the `options.` prefix in order to take up less space

![image](https://cloud.githubusercontent.com/assets/1210224/14151769/e2d9178a-f6af-11e5-8ee3-da7c13bccbd4.png)

It's still hella-long, but at least it's a bit easier to see what goes where - I also made the margins on the nested lists a bit smaller :)

**Comment by lipp** [comment]
:+1:  i like that! i think it's  good compromise between readability an space consumption. maybe the fullname (options.include.model) could be added as tooltip (on hover).

**Comment by lipp** [comment]
@janmeier nested params is online. maybe you could review and give feedback?

**Comment by janmeier** [comment]
Sure :)

![image](https://cloud.githubusercontent.com/assets/1210224/14229073/83211104-f929-11e5-95cc-82a9b54372dd.png)

This happens because of 
```
@param {Model} [options.include[].model] The model you want to eagerly load
```
Here `options.include` is an array of objects, and we are documenting the possible properties of the object - it seems the `[]` gets a separate item before the nested items are listed.

![image](https://cloud.githubusercontent.com/assets/1210224/14229083/afbc7af0-f929-11e5-9937-924577837bb6.png)


This happens because of 
```
@param {Object} [options.include[].through.where] Filter on the join model for belongsToMany relations
@param {Array}  [options.include[].through.attributes] A list of attributes to select from the join model for belongsToMany relations
```
Yes, even more nesting! :) The nesting itself actually works, but `through` disappears.

Already looking a lot better

**Comment by lipp** [comment]
@janmeier thanks for detailed report! :100:

**Comment by lipp** [comment]
@janmeier `through` disappears as `options.include[].through` is not documented with @param. not sure if this is "required" or if doclets should "auto-guess" the through must be an object... what do you think?

**Comment by janmeier** [comment]
@lipp That's definitely an error on our part then - We just never recognized it before because it worked fine with our homegrown docs script ;) - I'll add it and test again soon

**Comment by lipp** [comment]
@janmeier ok. anyhow, since doclets should try to be nice i added "augmenting" missing nested params parents. as children names imply the parent type this should work in all cases.

**Comment by lipp** [comment]
here you can see the "augmented" `through` param:
https://doclets.io/janmeier/sequelize/master#dl-Mixin-belongsToMany

hope you like it! thanks for reporting!!!
