### ISSUE TITLE
@see tag only partially supported

### ISSUE THREAD

**Issue by joscha** [lipp/doclets#83]
When using `@see`like this:

```
...
   * @see [finders/genericAnchors.js]{@link
   * https://github.com/crawlkit/crawlkit/blob/master/finders/genericAnchors.js}
   * for an example of a valid returned runnable function.
...
```

The result is only partially correct:
<img width="817" alt="crawlkit_-_master" src="https://cloud.githubusercontent.com/assets/188038/14158038/bf2ac56c-f719-11e5-8664-dcf3eadb54d8.png">

**Comment by lipp** [comment]
good catch! @joscha you seem to use the entire jsdoc tag spectrum :) . BTW: crawlkit seems very interesting and clean.

**Comment by lipp** [comment]
@joscha  this is fixed.
