### ISSUE TITLE
Extended type definitions linked incorrectly

### ISSUE THREAD

**Issue by joscha** [lipp/doclets#84]
A type definition like:
```
@type {!Object.<String,String>}
```
is transformed incorrectly to:
<img width="228" alt="crawlkit_-_master" src="https://cloud.githubusercontent.com/assets/188038/14158324/3d764008-f71b-11e5-9362-ba33dc72bd2c.png">

All three types should be linked independently (in the case of `Object`, `String` and `*` probably no link, as they are base types).
Also, the preceding `!` (non-null indicator) seems to be discarded and not to appear in the docs anywhere.

**Comment by lipp** [comment]
thanks for reporting!

**Comment by lipp** [comment]
@joscha is your example correct? if i read this (https://developers.google.com/closure/compiler/docs/js-for-compiler#types) correctly it probably should be `!Object<String, String>` (note the missing dot)?

**Comment by joscha** [comment]
I followed JSDoc: http://usejsdoc.org/tags-type.html which seems to have the dot if I understand correctly.

**Comment by lipp** [comment]
@joscha should be fixed for the most common cases.
some more advanced constructs are not working yet: record types `{{a: number, b: string, c}}` , `function` decls
BTW: do you know how to read this `{{a: number, b: string, c}}`? what does the `c` mean?

**Comment by lipp** [comment]
@joscha Improved the (extended) type linking stuff. However, JSDoc cripples the closure function decls and record decls :( 
i'll open a separate issue if these get supported by JSDoc.
